name: Nix demo

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pre-nix
      run: |
        node --version
    - name: Set up Nix environment
      uses: nix-community/nix-direnv@v1
    - name: Post-nix
      run: |
        node --version
